apiVersion: v1
name: postgres-operator-ui
version: 0.1.0
appVersion: 1.2.0
home: https://github.com/zalando/postgres-operator
description: Postgres Operator UI provides a graphical interface for a convenient database-as-a-service user experience
keywords:
- postgres
- operator
- ui
- cloud-native
- patroni
- spilo
maintainers:
- name: siku4
  email: sk@sik-net.de
sources:
- https://github.com/zalando/postgres-operator
engine: gotpl
